# Generated by Django 5.0.7 on 2024-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='8', max_length=100),
        ),
    ]
