# Generated by Django 5.0.7 on 2024-09-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_saved_wishlists_billing_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_company',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='order_comments',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='shipping_method',
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('paid_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.CharField(choices=[('Processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=30)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_company', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=100, null=True)),
                ('order_comments', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Checkout ',
            },
        ),
    ]
